import type { Metadata } from "next"
import { IBM_Plex_Sans_Thai } from "next/font/google"

import { cn } from "@/lib/utils"
import { Providers } from "@/components/providers"

import "./globals.css"

const fontSans = IBM_Plex_Sans_Thai({
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
  subsets: ["thai", "latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased", fontSans.variable)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
