import type { Metadata } from "next"
import { IBM_Plex_Mono, IBM_Plex_Sans_Thai } from "next/font/google"

import { cn } from "@/lib/utils"

import "./globals.css"

const fontSans = IBM_Plex_Sans_Thai({
  variable: "--font-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["thai", "latin"],
})

const fontMono = IBM_Plex_Mono({
  variable: "--font-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased", fontSans.variable, fontMono.variable)}>
        {children}
      </body>
    </html>
  )
}
